name: Add Issue

on:
  issues:
    types: [opened]

jobs:
  add-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Issue
      run: |
        echo "Adding issue to repository..."
        cat .github/workflows/Issues.md >> $GITHUB_EVENT_PATH
